### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by syntapy** [syntapy/test-driven-web-app-template#1]
- [ ] add service health to client app's `depends_on` 
- [x] split x11 configs to separate config file
- [x] shorter names for compose configs, e.g. `base.yml` instead of `docker-compose.base.yml`
- [ ] use [lifecycle hooks](https://docs.docker.com/compose/how-tos/lifecycle/)
- [ ] can [network mode](https://docs.docker.com/reference/compose-file/services/#network_mode) allow me to not use the up command?
- [ ] build with docker compose, not just docker
- [x] docker command can be passed as argument to `up_app` and `run_*` scripts in bin/
- [ ] stop setting entry & command in .env file
- [ ] fix .env path in `bin/lib/read_env`
- [ ] add runable example code using cypress
